# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Damaged', 'Damaged'), ('Dormant', 'Dormant')], max_length=30)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(default='Null', max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('joining_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student'), ('Other', 'Other')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=40)),
                ('route_id', models.CharField(max_length=40)),
                ('stop_id', models.CharField(max_length=10)),
                ('user_role', models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Staff', 'Staff')], max_length=30)),
            ],
        ),
    ]
