# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_databases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
