# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(max_length=10),
        ),
    ]
